In [1]:
import numpy as np

In [2]:
def generate_data():
    total_series_length = 50
    echo_step = 2  # 2-back task
    batch_size = 1
    x = np.random.choice(2, total_series_length, p=[0.5, 0.5])
    y = np.roll(x, echo_step)
    y[0:echo_step] = 0
    y = list(y)
    return (x, y)

In [3]:
def cost(x,y,U,V,w):
    
    y_hat,h = forward(x,y,U,V,w)
#     print("Y_HAT",max(y_hat),min(y_hat))
#     print("Y",y)
#     print("delta",(y-y_hat))
    cost = (1/2) * np.sum((y_hat.T[0] - y)**2)
    return cost

In [4]:
def forward(x,y,U,V,w):
    w = w.reshape(6,1)
#         print("Shape of U",self.U.shape)
#         print("Shape of V",self.V.shape)
#         print("Shape of W",self.w.shape)
        
    T = len(x)
    h = np.zeros((T+1,numHidden))
    h[-1] = np.zeros((numHidden))
    y_hat = np.zeros((T,1))
    z_t = np.zeros((T+1,numHidden))

#         print("Shape of H",h.shape)
#         print("Shape of Z",z_t.shape)
#         print("Shape of H[t]",h[0].shape)

    for t in np.arange(T):
        part1 = (np.dot(U,(h[t-1].reshape(6,1)))).reshape(1,6)
        part2 = np.dot(V,x[t]).reshape(1,6)

        z_t[t] = (part1 + part2)

        h[t] = np.tanh(z_t[t])
        y_hat[t] = np.dot(h[t],w)

#         print("Shape of y_hat",y_hat.shape)    

    return y_hat,h

In [18]:
def backward (x,y,U,V,w):
    T = len(y)
    y_hat,h = forward(x,y,U,V,w)
    w = w.reshape(6,1)    
    dJdU = np.zeros(U.shape)
    dJdV = np.zeros(V.shape)
    dJdW = np.zeros(w.shape)
#     print("Shape of Y",len(y))
#     print("Shape of Y_HAT",y_hat.shape)
#     print("Shape of H",h[0].shape)
    y = np.asarray(y).reshape(len(y),1)
    delta = (y_hat-y)

#     print("Shape of DELTA",delta)
    for t in np.arange(T):
        dJdW += delta[t]*(h[t].reshape(6,1))

        delta_t = w.dot(delta[t])*(1-h[t]**2)
        print(np.arange(max(0,t-4),t+1)[::-1])
        for step in np.arange(max(0,t-4),t+1)[::-1]:
            print(step)
            dJdU += np.outer(delta_t,h[step]-1)
            dJdV[:,x[step]-1] += delta_t

            delta_t = U.T.dot(delta_t)*(1-h[step-1]**2)

    return [dJdW,dJdU,dJdV]

In [13]:
d=np.zeros(6)
d+=1
d

array([1., 1., 1., 1., 1., 1.])

In [15]:
def update_sgd(x,y,U,V,w):
    w = w.reshape(6,1)
    dW,dU,dV = backward(x,y,U,V,w)
    print(dW, dU, dV)
    w -= (1e-1*dW)
    U -= (1e-5*dU)
    V -= (1e-7*dV)

In [6]:
def train(x,y,U,V,w,epoch):
    costs = []
    for i in np.arange(0,epoch):
        for j in np.arange(len(y)):
            update_sgd(x,y,U,V,w)
            print("Cost :",cost(x,y,U,V,w))

In [19]:
numHidden = 6
numInput = 1
x,y = generate_data()
x = np.asarray(x)
y = np.asarray(y)
U = np.random.randn(numHidden, numHidden) * 1e-1
V = np.random.randn(numHidden, numInput) * 1e-1
w = np.random.randn(numHidden) * 1e-1
backward(x,y,U,V,w)
#train(x,y,U,V,w,250)

[0]
0
[1 0]
1
0
[2 1 0]
2
1
0
[3 2 1 0]
3
2
1
0
[4 3 2 1 0]
4
3
2
1
0
[5 4 3 2 1]
5
4
3
2
1
[6 5 4 3 2]
6
5
4
3
2
[7 6 5 4 3]
7
6
5
4
3
[8 7 6 5 4]
8
7
6
5
4
[9 8 7 6 5]
9
8
7
6
5
[10  9  8  7  6]
10
9
8
7
6
[11 10  9  8  7]
11
10
9
8
7
[12 11 10  9  8]
12
11
10
9
8
[13 12 11 10  9]
13
12
11
10
9
[14 13 12 11 10]
14
13
12
11
10
[15 14 13 12 11]
15
14
13
12
11
[16 15 14 13 12]
16
15
14
13
12
[17 16 15 14 13]
17
16
15
14
13
[18 17 16 15 14]
18
17
16
15
14
[19 18 17 16 15]
19
18
17
16
15
[20 19 18 17 16]
20
19
18
17
16
[21 20 19 18 17]
21
20
19
18
17
[22 21 20 19 18]
22
21
20
19
18
[23 22 21 20 19]
23
22
21
20
19
[24 23 22 21 20]
24
23
22
21
20
[25 24 23 22 21]
25
24
23
22
21
[26 25 24 23 22]
26
25
24
23
22
[27 26 25 24 23]
27
26
25
24
23
[28 27 26 25 24]
28
27
26
25
24
[29 28 27 26 25]
29
28
27
26
25
[30 29 28 27 26]
30
29
28
27
26
[31 30 29 28 27]
31
30
29
28
27
[32 31 30 29 28]
32
31
30
29
28
[33 32 31 30 29]
33
32
31
30
29
[34 33 32 31 30]
34
33
32
31
30
[35 34 33 32 31]
35
34
33
32
3

[array([[-2.11873346],
        [ 0.0993065 ],
        [-0.47150767],
        [ 0.09508707],
        [ 0.20343214],
        [-1.2280936 ]]),
 array([[ 0.69863432,  0.77982777,  0.7551751 ,  0.78227721,  0.78019845,
          0.72342751],
        [ 3.43775687,  3.76934792,  3.68007439,  3.77308138,  3.78233797,
          3.56700815],
        [ 2.13608811,  2.35113539,  2.28698229,  2.35889043,  2.35445989,
          2.20952988],
        [-2.25046775, -2.46625693, -2.41258396, -2.46449187, -2.47804955,
         -2.34081012],
        [-0.184086  , -0.20959377, -0.20395835, -0.20805504, -0.21110882,
         -0.19404   ],
        [ 0.52707683,  0.5878514 ,  0.56194685,  0.59695056,  0.58262976,
          0.53566314]]),
 array([[-0.77749303],
        [-3.75655663],
        [-2.34542009],
        [ 2.45592879],
        [ 0.20777091],
        [-0.58956528]])]